#### Numpy
NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

In [ ]:
!pip install numpy

In [73]:
import numpy as np

## create array using numpy
##create a 1D array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [74]:
## 1 d array
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)  ##1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [75]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [76]:
## 2d array
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [92]:
print(np.arange(2,10,2).reshape(2,2))

[[2 4]
 [6 8]]


In [86]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [ ]:
np.ones((3,4))

In [ ]:
## identity matrix
np.eye(3)

In [98]:
print(np.ones((2,2)))
print(np.zeros((3,3)))
print(np.eye(4))

[[1. 1.]
 [1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [108]:
# attributes
a=np.array([[1,2,3],[4,5,6]])
print(a)
print('shape', a.shape)
print(a.ndim)
print("size:",a.size)
print(a.dtype)
print(a.itemsize)

[[1 2 3]
 [4 5 6]]
shape (2, 3)
2
size: 6
int32
4


In [ ]:
## Attributes of Numpy Array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)  # Output: (2, 3)
print("Number of dimensions:", arr.ndim)  # Output: 2
print("Size (number of elements):", arr.size)  # Output: 6
print("Data type:", arr.dtype)  # Output: int32 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize)  # Output: 8 (may vary based on platform)


In [ ]:
### Numpy Vectorized Operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

### Element Wise addition
print("Addition:", arr1+arr2)

## Element Wise Substraction
print("Substraction:", arr1-arr2)

# Element-wise multiplication
print("Multiplication:", arr1 * arr2)

# Element-wise division
print("Division:", arr1 / arr2)

In [ ]:
## Universal Function
arr=np.array([2,3,4,5,6])
## square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sine
print(np.sin(arr))

## natural log
print(np.log(arr))

In [ ]:
## array slicing and Indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n", arr)



In [ ]:
print(arr[1:,1:3])

In [ ]:
print(arr[0][0])
print(arr[0:2,2:])

In [ ]:
arr[1:,2:]

In [ ]:
## Modify array elements
arr[0,0]=100
print(arr)

In [ ]:
arr[1:]=100
print(arr)

In [ ]:
### statistical concepts--Normalization
##to have a mean of 0 and standard deviation of 1
data = np.array([1, 2, 3, 4, 5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)



In [ ]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)



In [ ]:
## Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]

## Practice

In [ ]:
import numpy as np

In [ ]:
# creating 1d array
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

In [ ]:
# shape and data type
print(arr.shape)

In [ ]:
print(arr.dtype)

In [ ]:
# creating 1d, 2d. 3d array

arr1=np.array([1,2,3,4])
arr2=np.array([[1,2,3],[4,5,6]])
arr3=np.array([[[1,2,3],[4,5,6]]])

In [ ]:
print(arr1)
print(arr2)
print(arr3)

In [ ]:
# special arrays
np.ones((5,3))

In [ ]:
np.zeros((2,3))

In [ ]:
np.eye(4)

In [ ]:
np.full((2,3),4)

In [ ]:
np.random.randn(3,3)    # standard normal distribution

In [ ]:
np.random.randint(1,100,(3,5))     # random numbers betweeen a range

In [ ]:
np.random.rand(3,3)  # random numbers btween 0 and 1

In [ ]:
#   element wise operations
arr1=np.array([1,2,3,4,5])
arr2=np.array([5,6,7,8,9])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

In [ ]:
# aggregate functions

arr=np.array([[1,2,3],[4,5,6]])
print(np.sum(arr))
print(np.max(arr))
print(np.min(arr))
print(np.std(arr))
print(np.mean(arr))
print(np.median(arr))

In [ ]:
# linear algerbra
a=np.array([[1,2],[3,2]])
b=np.array([[4,5],[4,5]])
np.dot(a,b)

In [ ]:
np.matmul(a,b)

In [ ]:
a@b

In [ ]:
print(np.linalg.det(a))

In [ ]:
print(np.linalg.inv(a))

In [ ]:
a=np.arange(1,10)
print(a)

In [ ]:
np.where(a>5,'true','false')

In [ ]:
a[a>5]

In [ ]:
# nan values
a=np.array([1,2,3,np.nan,4,np.nan])
print(a)
a[np.isnan(a)]=0
print(a)

In [ ]:
np.linspace(0,10,5)

In [ ]:
a=np.arange(1,10)
print(a)

In [ ]:
b=a.reshape((3,3))
print(b)

In [ ]:
b.flatten()