#### Numpy
NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

In [ ]:
!pip install numpy

In [73]:
import numpy as np

## create array using numpy
##create a 1D array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [74]:
## 1 d array
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)  ##1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [75]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [76]:
## 2d array
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [92]:
print(np.arange(2,10,2).reshape(2,2))

[[2 4]
 [6 8]]


In [86]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [ ]:
np.ones((3,4))

In [ ]:
## identity matrix
np.eye(3)

In [98]:
print(np.ones((2,2)))
print(np.zeros((3,3)))
print(np.eye(4))

[[1. 1.]
 [1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [108]:
# attributes
a=np.array([[1,2,3],[4,5,6]])
print(a)
print('shape', a.shape)
print(a.ndim)
print("size:",a.size)
print(a.dtype)
print(a.itemsize)

[[1 2 3]
 [4 5 6]]
shape (2, 3)
2
size: 6
int32
4


In [ ]:
## Attributes of Numpy Array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)  # Output: (2, 3)
print("Number of dimensions:", arr.ndim)  # Output: 2
print("Size (number of elements):", arr.size)  # Output: 6
print("Data type:", arr.dtype)  # Output: int32 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize)  # Output: 8 (may vary based on platform)


In [109]:
### Numpy Vectorized Operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

### Element Wise addition
print("Addition:", arr1+arr2)

## Element Wise Substraction
print("Substraction:", arr1-arr2)

# Element-wise multiplication
print("Multiplication:", arr1 * arr2)

# Element-wise division
print("Division:", arr1 / arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [110]:
## Universal Function
arr=np.array([2,3,4,5,6])
## square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sine
print(np.sin(arr))

## natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [ ]:
## array slicing and Indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n", arr)



Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [113]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [114]:
print(arr[0][0])
print(arr[0:2,2:])

1
[[3 4]
 [7 8]]


In [115]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [116]:
## Modify array elements
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [117]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [119]:
### statistical concepts--Normalization
##to have a mean of 0 and standard deviation of 1
data = np.array([1, 2, 3, 4, 5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)



Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [120]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)



Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [121]:
## Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])

## Practice

In [122]:
import numpy as np

In [123]:
# creating 1d array
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [124]:
# shape and data type
print(arr.shape)

(5,)


In [125]:
print(arr.dtype)

int32


In [126]:
# creating 1d, 2d. 3d array

arr1=np.array([1,2,3,4])
arr2=np.array([[1,2,3],[4,5,6]])
arr3=np.array([[[1,2,3],[4,5,6]]])

In [127]:
print(arr1)
print(arr2)
print(arr3)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]]


In [128]:
# special arrays
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [129]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [130]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [131]:
np.full((2,3),4)

array([[4, 4, 4],
       [4, 4, 4]])

In [132]:
np.random.randn(3,3)    # standard normal distribution

array([[-0.95793383, -1.28468444,  1.33317663],
       [ 1.0592829 , -0.05085995,  1.31037015],
       [ 0.70742973, -0.8248919 ,  1.14022871]])

In [133]:
np.random.randint(1,100,(3,5))     # random numbers betweeen a range

array([[76, 89, 11, 96, 18],
       [40,  7, 19,  1, 44],
       [ 4, 71, 58, 97, 81]])

In [134]:
np.random.rand(3,3)  # random numbers btween 0 and 1

array([[0.84192272, 0.05999573, 0.782822  ],
       [0.94841499, 0.27292753, 0.43786808],
       [0.91147432, 0.58840515, 0.04013058]])

In [135]:
#   element wise operations
arr1=np.array([1,2,3,4,5])
arr2=np.array([5,6,7,8,9])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[ 6  8 10 12 14]
[-4 -4 -4 -4 -4]
[ 5 12 21 32 45]
[0.2        0.33333333 0.42857143 0.5        0.55555556]


In [137]:
# aggregate functions

arr=np.array([[1,2,3],[4,5,6]])
print(np.sum(arr))
print(np.max(arr))
print(np.min(arr))
print(np.std(arr))
print(np.mean(arr))
print(np.median(arr))

21
6
1
1.707825127659933
3.5
3.5


In [138]:
# linear algerbra
a=np.array([[1,2],[3,2]])
b=np.array([[4,5],[4,5]])
np.dot(a,b)

array([[12, 15],
       [20, 25]])

In [139]:
np.matmul(a,b)

array([[12, 15],
       [20, 25]])

In [140]:
a@b

array([[12, 15],
       [20, 25]])

In [141]:
print(np.linalg.det(a))

-4.000000000000001


In [142]:
print(np.linalg.inv(a))

[[-0.5   0.5 ]
 [ 0.75 -0.25]]


In [143]:
a=np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [144]:
np.where(a>5,'true','false')

array(['false', 'false', 'false', 'false', 'false', 'true', 'true',
       'true', 'true'], dtype='<U5')

In [145]:
a[a>5]

array([6, 7, 8, 9])

In [146]:
# nan values
a=np.array([1,2,3,np.nan,4,np.nan])
print(a)
a[np.isnan(a)]=0
print(a)

[ 1.  2.  3. nan  4. nan]
[1. 2. 3. 0. 4. 0.]


In [147]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [148]:
a=np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [149]:
b=a.reshape((3,3))
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [150]:
b.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])